### ISSUE TITLE
Ability to set profile, jvm parameters, system properties  

### ISSUE THREAD

**Issue by rinfimate** [microsoft/vscode-spring-boot-dashboard#104]
The App launch parameters should be configurable to add spring profiles, jvm parameters and other java system properties

**Comment by Eskibear** [comment]
Ultimately you can set anything you want via `launch.json`.  If you think some UI things do help, please let us know your expectation of the experience.

**Comment by jorgemoralespou** [comment]
At least it would be nice if you right-click on the application on the dashboard and would open the launch.json for editing, pointing to the right profile.

**Comment by usersina** [comment]
I also noticed that the dashboard was ignoring my `<spring-boot.run.jvmArguments>-Duser.timezone=UTC</spring-boot.run.jvmArguments>` in `pom.xml` so the ability to set JVM arguments or at least not ignore the ones already set would be a great addition.

I tried `"vmArgs": "-Duser.timezone=UTC"` [as described here](https://stackoverflow.com/a/60044053/10543130) and it does not work. I had to make due with creating a [`launch.json`](https://stackoverflow.com/a/74696142/10543130)
