### ISSUE TITLE
feature request: stop all running apps

### ISSUE THREAD

**Issue by Eskibear** [microsoft/vscode-spring-boot-dashboard#107]
from: https://github.com/microsoft/vscode-spring-boot-dashboard/issues/28#issuecomment-638321659  by @brunovieira97 

I think adding a "stop" button should work. It's on title bar of the explorer, with confirmation poped up, in case of clicking by mistake. Is that enough, or any concern?

**Comment by brunovieira97** [comment]
Sure! It could work the same as Start does, with checkboxes. Is that possible?

**Comment by Eskibear** [comment]
Agreed. Using checkboxes is more flexible.
