### ISSUE TITLE
Feature request: Multiple apps start order

### ISSUE THREAD

**Issue by brunovieira97** [microsoft/vscode-spring-boot-dashboard#108]
I've started using the extension recently. I'm working with a collection of microservices, and there's a specific launch order. Is it possible to specify this?

**Example:**
 1. start serviceA
 2. start serviceB
 3. start any other services (no order necessary)

I see this as an advanced config for launching multiple apps, like a launch.json with dependencies listed for each app, or even a more complex flow (as listed above).

With such functionality, my Code Workspace with these multiple microservices would be launched with a single click on Start, selecting all services I want to launch, and the extension (or VS Code) would resolve the startup order dependencies by itself.

**Comment by Eskibear** [comment]
VS Code does support the compound launch of multiple apps, and you should config that in `launch.json` file. You can refer to https://code.visualstudio.com/docs/editor/debugging#_compound-launch-configurations .

BUT, according to my experience, the apps are started together, and currently there is no way to define dependencies between launch configuration entries.

**Comment by kdvolder** [comment]
> define dependencies between launch configuration entries.

Also, arguably, it is a good idea to design apps in such a way that they do not have complex startup time dependencies. This also fits in with 'fault tolerance' which is also a good idea when designing 'microservices' architectures. I.e. when app A requires a service from app B, generally you would want app A to be somewhat tolerant of app B going down/missing anyway and app A should deal with such situations gracefully and should start working (again) when the service provided by app B is restored. If apps/services are designed with this sort of thing in mind, then it shouldn't really matter what order your apps are being started in.

**Comment by brunovieira97** [comment]
In my case, microservice apps depend on a Config Server that delivers config files for each app that starts. My main point is to see if there's an option so I can set this dependency so I can safely start the other apps only after the Config Server is up.

**Comment by kdvolder** [comment]
@brunovieira97 Maybe this is helpful: https://cloud.spring.io/spring-cloud-config/multi/multi__spring_cloud_config_client.html#config-client-retry

There are ways I think to make the config client retry for some time if the server is not available. Thereby I think you can effectively make it 'wait for the server' and avoid manually micro managing to start things in the right order.
