### ISSUE TITLE
Spring boot apps always start in debug mode

### ISSUE THREAD

**Issue by bobonis** [microsoft/vscode-spring-boot-dashboard#109]
Using version 1.46.0 of VS Code and 0.1.10 of Spring Boot Dashboard.

Right clicking on an application under Spring Boot Dashboard and selecting **Start**, it will start the debugger as if I had clicked on **Debug**. The issue appeared after last update of VS Code.

The same behavior appears when using Java Test Runner plugin if it helps.

As a workaround, key combination Ctrl+F5 can be used to start an application in normal mode.

**Comment by Eskibear** [comment]
Thank you for reporting it, I can reproduce it.   also cc @jdneo for awareness.

**Comment by jdneo** [comment]
@testforstephen FYI

**Comment by jdneo** [comment]
See https://github.com/microsoft/vscode/issues/99958

**Comment by Eskibear** [comment]
fixed in upstream https://github.com/microsoft/vscode/issues/100364
