### ISSUE TITLE
Debug .jar file in vscode

### ISSUE THREAD

**Issue by r00bit** [microsoft/vscode-spring-boot-dashboard#110]
Hi all, 
How can I debug a .jar file without source code .java through vscode?
Do I need to do reverse engineering?

**Comment by Eskibear** [comment]
Java Debugger extension is responsible for that. https://github.com/microsoft/vscode-java-debug/issues should be the place to go.
And there might be 3rd-party decompiler extensions in marketplace, you can take a look.
