### ISSUE TITLE
Kotlin support

### ISSUE THREAD

**Issue by liron-navon** [microsoft/vscode-spring-boot-dashboard#113]
Hello, more than a year have passed since last discussed about Kotlin for this extension, are there any plans to add Kotlin support?

https://github.com/microsoft/vscode-spring-boot-dashboard/issues/63

**Comment by Eskibear** [comment]
See https://github.com/microsoft/vscode-spring-boot-dashboard/issues/63#issuecomment-559637756 and https://github.com/spring-projects/sts4/issues/163#issuecomment-690911486
