### ISSUE TITLE
Can't stop Running Spring Boot App

### ISSUE THREAD

**Issue by JohnSeals** [microsoft/vscode-spring-boot-dashboard#114]
Issue Type: <b>Bug</b>

I have an issue where I can start a Spring Boot application with Spring-Boot Dashboard but once it's running there is no easy way to stop it. The Spring-Boot Dashboard options are only "Start" and "Debug" and there is no "red square" availabe next to the running app in the Dashboard either. I have to close the app via the terminal with an "lsof" command.

This might not seem like much but it's a huge pain! I'm trying to convince co-workers to move to VSCode from Intellij IDEA and Eclipse.

Thanks!

Extension version: 0.1.10
VS Code version: Code 1.50.1 (d2e414d9e4239a252d1ab117bd7067f125afd80a, 2020-10-13T14:53:05.704Z)
OS version: Darwin x64 19.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 5, 5|
|Memory (System)|16.00GB (0.46GB free)|
|Process Argv|--crash-reporter-id 3e67cd3c-5ffe-4e78-b6f9-af4e1d0d07b5|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by Eskibear** [comment]
You can either click the "stop" button on top of the window.
![image](https://user-images.githubusercontent.com/2351748/97124809-90e89300-176c-11eb-94dc-1f911f2e068b.png)

Or right click your project, and click "Stop"
![image](https://user-images.githubusercontent.com/2351748/97124819-9e058200-176c-11eb-90a0-f060d1e9386d.png)

**Comment by JohnSeals** [comment]
That’s what I was trying to describe. I am not seeing those options on my install.

**Comment by Eskibear** [comment]
It's strange, the menu items are statically registered. Can you try https://github.com/spring-projects/spring-petclinic on your machine, see if it's related to your project?
Or can you just share a sample project for me to reproduce the issue?

**Comment by JohnSeals** [comment]
> It's strange, the menu items are statically registered. Can you try https://github.com/spring-projects/spring-petclinic on your machine, see if it's related to your project?
> Or can you just share a sample project for me to reproduce the issue?

It was my project. Everything works great in Petclinic. 

Thanks so much for your speedy reply. Sorry to have bothered you!!!!

**Comment by JohnSeals** [comment]
CLOSED. Was happening only to projects created by our team. Suspect some kind of config issue.
