### ISSUE TITLE
How to stop a SpringBoot Application start with wrong args?

### ISSUE THREAD

**Issue by rainbowechoes** [microsoft/vscode-spring-boot-dashboard#119]
In my project, I start a config server in 8881 port, so when I start my business Application , it will fetch config from localhost:8888 forever. So I want to know how to stop this business application.

**Comment by Eskibear** [comment]
In the SpringBoot Dashboard explorer, you can see all spring boot project in your workspace and you are able to start/stop them there.

If that's not your case, please describe the steps how you start the application, what's the actual behavior and what's your expected behavior.

**Comment by rainbowechoes** [comment]
thanks, I have find the way to resolve
