### ISSUE TITLE
dashboard can not  boot   springboot project

### ISSUE THREAD

**Issue by tgl123** [microsoft/vscode-spring-boot-dashboard#122]
1.application is springboot prjoject ApiApplication
2. I click dashboard  button start or debug, then show me  :
错误: 找不到或无法加载主类 com.sico.api.ApiApplication
原因: java.lang.ClassNotFoundException: com.sico.api.ApiApplication

3， if i  excute command  : mvn package,  then click  start or debug  button，project run success

4. why  dashboard cannot automated compling project?

**Comment by Eskibear** [comment]
Java extension is responsible for importing and compiling the project, and Debugger for Java extension is responsible for runnning and debugging. 

Can you provide below information?
* list of installed extensions.
* "java" related settings.
* content of `.vscode/launch.json` (if exists)

**Comment by an-tho-ny** [comment]
Hi I think I have the same problem I but I posted it here #129.

**Comment by tgl123** [comment]
1.list of installed extensions.
![image](https://user-images.githubusercontent.com/7203683/112862582-81d58a80-90e8-11eb-8084-4b2479ed8b35.png)


2  java verison:
openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)
==========

3  lauch.json
===========
{
    "configurations": [
        {
            "type": "java",
            "name": "Spring Boot-ApiApplication<api>",
            "request": "launch",
            "cwd": "${workspaceFolder}",
            "console": "internalConsole",
            "mainClass": "com.ftdx.api.ApiApplication",
            "projectName": "api",
            "args": ""
        }
    ]
}

**Comment by Eskibear** [comment]
@tgl123 [Java Extension](https://marketplace.visualstudio.com/items?itemName=redhat.java) is responsible to compile your project, and [Java Debugger extension](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-debug) is responsible to run/debug your project based on `launch.json` file.  You mentioned your project was not compiled automatically, maybe you have some specific[ java related settings](https://github.com/redhat-developer/vscode-java/#supported-vs-code-settings)? e.g. 
> java.autobuild.enabled : Enable/disable the 'auto build'.

**Comment by Eskibear** [comment]
@an-tho-ny  If you cannot list your spring boot projects, please see: https://github.com/spring-projects/sts4/issues/612#issuecomment-802798311

**Comment by tgl123** [comment]
setting.json
![image](https://user-images.githubusercontent.com/7203683/112925008-b75b9180-9143-11eb-8796-a103647f2d4f.png)

**Comment by Eskibear** [comment]
![image](https://user-images.githubusercontent.com/2351748/112925963-52a13680-9145-11eb-830f-a5937cf90be5.png)

Try disabling this extension?

**Comment by tgl123** [comment]
Java language Support  extension is not install!
![image](https://user-images.githubusercontent.com/7203683/112926336-e246e500-9145-11eb-9e2e-35d569037472.png)

**Comment by tgl123** [comment]
@Eskibear  
 you  can manually:   (1) mvn clean   (2)   then  run debug(spring boot dashboard)
 the project run success?

**Comment by Eskibear** [comment]
AFAIK, auto compilation doesn't listen to changes of target folder. If you remove all the files through other tools e.g. `mvn clean`, of course there won't be .class files, thus "main class" will not be found.

You can open command palette (F1) --> "Java: Force Java Compilation" --> "Full". It should re-compile the project and create corresponding .class files.

**Comment by tgl123** [comment]
Yes, I  do    "Java: Force Java Compilation" --> "Full"
project run success！ I think   when  springboot dashboard  can froce java,  It be better!
thanks Eskibear!

**Comment by Eskibear** [comment]
Well, it's behavior of the Java extension. 

> every time ,I must do this step:Java: Force Java Compilation.

It makes sense to me. Suppose you want to remove target folder manually. If Java extension listens to all file changes and forces complilation, you are not going to remove the folder successfully. That could be a more wired situation.

**Comment by an-tho-ny** [comment]
> 
> 
> @an-tho-ny If you cannot list your spring boot projects, please see: [spring-projects/sts4#612 (comment)](https://github.com/spring-projects/sts4/issues/612#issuecomment-802798311)

Ok, Thanks Eskibear.
