### ISSUE TITLE
Not detecting Spring app

### ISSUE THREAD

**Issue by victor-k-lee** [microsoft/vscode-spring-boot-dashboard#123]
Issue Type: <b>Bug</b>

keep loading , not thing show.

Extension version: 0.2.0
VS Code version: Code 1.54.3 (2b9aebd5354a3629c3aba0a5f5df49f43d6689f8, 2021-03-15T10:55:45.459Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.76GB (7.56GB free)|
|Process Argv|--crash-reporter-id f15158c2-274e-4913-88d8-9b0cc893e8ee|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstry914:30276682
pythonvsdeb440:30248342
pythonvsded773:30248341
pythonvspyt875:30259475
dockersubset:30270708
pythontbcf:30265426
vscoresta800cf:30276762
vspre833cf:30267465
vsdfh931:30275552

```

</details>

**Comment by Eskibear** [comment]
> keep loading 

what do you mean by above? Can you share more information(e.g. screenshot) about what was loading?

**Comment by victor-k-lee** [comment]
It no longer detect springboot apps, I tried remove everything(.m2, viscose extension folder etc) and start from scratch, still not detecting. 

The loading bar under the "springboot dashboard" keep running while the "explorer" (file) icon showed a clock icon (loading) and never go away until restart vscode.

Springboot can still run from vscode menu.

**Comment by jjune1207** [comment]
Suddenly the spring boot dashboard loads indefinitely and does not show the project icon.

However, the execution project can be executed from the main thread execution location.

**Comment by Eskibear** [comment]
Possibly because of this: https://github.com/spring-projects/sts4/issues/612

Can you follow https://github.com/spring-projects/sts4/issues/612#issuecomment-802798311 , see if you can work it around?
