### ISSUE TITLE
Spring Boot Dashboard keeps spinning instead of showing applications

### ISSUE THREAD

**Issue by tigerinus** [microsoft/vscode-spring-boot-dashboard#124]
Not sure if this is the same issue as #123 

In the extension output it says

```
Activating 'vscode-spring-boot' extension
Found java exe: /home/tigerinus/.local/jdk1.8.0_261/bin/java
isJavaEightOrHigher => true
Redirecting server logs to /dev/null
ERR: Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/springframework/ide/vscode/boot/app/BootLanguagServerBootApp has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:601)
```

I need more guide on what information to provide for troubleshooting.

Thanks!

**Comment by Eskibear** [comment]
> Activating 'vscode-spring-boot' extension

The error is from Spring Tools extension: https://github.com/spring-projects/sts4/tree/master/vscode-extensions/vscode-spring-boot . 

> Exception in thread "main" java.lang.UnsupportedClassVersionError: org/springframework/ide/vscode/boot/app/BootLanguagServerBootApp has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

class file version 55.0 is corresponding to Java 11, and 52.0 is Java 8. As far as I know [Java extension](https://github.com/redhat-developer/vscode-java/) is responsible to compile projects. It's probably that your project was previously compiled with Java 11, but now you are using Java 8. 

One approach you can try is to clean up your workspace using below command.
![image](https://user-images.githubusercontent.com/2351748/111555104-a5343780-87c2-11eb-9919-f9808442c415.png)

Let me know if it works.

**Comment by rybertm-old** [comment]
> One approach you can try is to clean up your workspace using below command.
> ![image](https://user-images.githubusercontent.com/2351748/111555104-a5343780-87c2-11eb-9919-f9808442c415.png)
> 
> Let me know if it works.

Hi, I'm facing the same issue, tried your suggestion but it did not work. This problem wasn't occurring couple of days ago and my workspace/projects didn't change.

For reference I'm using JDK 15 for Language Server Features(JDK 11+ required) and my workspace has 2 projects using JDK 1.8, which I have configured in the Java Extension.

**Comment by tigerinus** [comment]
> > Activating 'vscode-spring-boot' extension
> 
> The error is from Spring Tools extension: https://github.com/spring-projects/sts4/tree/master/vscode-extensions/vscode-spring-boot .
> 
> > Exception in thread "main" java.lang.UnsupportedClassVersionError: org/springframework/ide/vscode/boot/app/BootLanguagServerBootApp has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
> 
> class file version 55.0 is corresponding to Java 11, and 52.0 is Java 8. As far as I know [Java extension](https://github.com/redhat-developer/vscode-java/) is responsible to compile projects. It's probably that your project was previously compiled with Java 11, but now you are using Java 8.
> 
> One approach you can try is to clean up your workspace using below command.
> ![image](https://user-images.githubusercontent.com/2351748/111555104-a5343780-87c2-11eb-9919-f9808442c415.png)
> 
> Let me know if it works.

It didn't work. I use JAVA 8 only. I have JAVA 11 installed but that's required by Redhat Java extension, but I am sure my project is using JAVA 8 path everywhere.

**Comment by Eskibear** [comment]
@tigerinus My bad. The error message was provided during activation of Spring Boot Tools, thus it should has nothing to do with your projects or Java extension.


> This problem wasn't occurring couple of days ago ..

@rybertm-old Thank you for the feedbacks. I notice that [Spring Boot Tools](https://marketplace.visualstudio.com/items?itemName=Pivotal.vscode-spring-boot) extension has shipped a new version in Mar. 17, and I think it's likely to be related.



@martinlippert Can you take a look? It seems that Spring Boot Language Server was not successfully activated. Below is the error message in user's output window, see full log in original description above.

> Exception in thread "main" java.lang.UnsupportedClassVersionError: org/springframework/ide/vscode/boot/app/BootLanguagServerBootApp has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

**Comment by Eskibear** [comment]
similar issue here : https://github.com/spring-projects/sts4/issues/612

**Comment by martinlippert** [comment]
@Eskibear Yes, the new version of the Spring Tools extension for VSCode requires a JDK >= 11 to run on, but the internal check to verify that hasn't been updated. We will fix that check, as mentioned in https://github.com/spring-projects/sts4/issues/612. Thanks for pointing this out.

**Comment by martinlippert** [comment]
Please keep in mind here that the extension itself requires a JDK >= 11 to run on (in a similar way than the Java Language Support for VSCode) and you can configure that in the settings. This is completely unrelated to the JDK that your projects need to compile against and run on. They can, of course, stay on JDK8.

**Comment by martinlippert** [comment]
The name of the property to configure the JVM that the Spring Boot Language Server uses to run itself is: `"spring-boot.ls.java.home"` and can be configured in your `settings.json` file.

**Comment by tigerinus** [comment]
> The name of the property to configure the JVM that the Spring Boot Language Server uses to run itself is: `"spring-boot.ls.java.home"` and can be configured in your `settings.json` file.

This solved the problem. The projects are showing up in the dashboard again. Thanks.

**Comment by rybertm-old** [comment]
> The name of the property to configure the JVM that the Spring Boot Language Server uses to run itself is: `"spring-boot.ls.java.home"` and can be configured in your `settings.json` file.

This solved it for me too. Thanks for the help.

**Comment by tigerinus** [comment]
So why not have this extension to refer to `"java.home"` in the settings.json?

Having each Java related extension to have its own Java home setting seems unnecessary to me. Many newcomers switching over to VSCode from IntelliJ for their JDK8 projects will be very confused.
