### ISSUE TITLE
No applications listed in the spring boot dashboard view

### ISSUE THREAD

**Issue by Arthurzy** [microsoft/vscode-spring-boot-dashboard#127]
Hi，
I've added all extenions related to spring boot, but my spring boot dashboard cannot detect my spring boot application. it's just loading. Maven view and Java project view work fine except spring boot dashborad view.
So could you pleae help with that?
![screenshot](https://user-images.githubusercontent.com/50877216/112013953-6e18aa00-8b65-11eb-8123-edbb62491fcd.png)

**Comment by Eskibear** [comment]
Can you check output window "vscode-spring-boot-debug-log", see if there's similar error with https://github.com/microsoft/vscode-spring-boot-dashboard/issues/125 .

If so, follow https://github.com/spring-projects/sts4/issues/612#issuecomment-802798311 to work it around.

**Comment by Arthurzy** [comment]
I added spring-boot.ls.java.home variable to the seeting.json. and it works. thanks
