### ISSUE TITLE
Toolbar closing automatically after changing console to integratedTerminal

### ISSUE THREAD

**Issue by Uttam92477** [microsoft/vscode-spring-boot-dashboard#128]
### Steps to reproduce
- Install vscode on windows machine
- Install spring extensions (along with spring-boot-dashboard)
- Create a sample spring project
- Change launch.json to use integratedTerminal instead of integratedConsole
  - I am using git bash as integrated terminal
- Start spring project using spring boot dashboard
The tool bar which allows stop, restart etc appears until the spring project starts and then automatically closes (the spring application is still running)

**Comment by Eskibear** [comment]
> Start spring project using spring boot dashboard

I believe it's VS Code's behavior as you are running it instead of debugging it. Right click on the project, select "debug", see if toolbar still disappear after that ?
