### ISSUE TITLE
Spring Boot Dashboard couldn't list project

### ISSUE THREAD

**Issue by naveenroy001** [microsoft/vscode-spring-boot-dashboard#129]
Spring Boot Dashboard Extention cannot list spring project it continues finding project but couldn't resolve project and couldn't generate launch.json 

##### Environment
- Operating System: Windows 10
- JDK version: 11 and 8
- Visual Studio Code version: 1.54.3
- Java extension version:  0.2.0
- Java Debugger extension version: 0.32.1

##### Steps To Reproduce
1. Add Existing Spring Boot Project
2. Goto Spring Dashboard Extension

##### Project Details
Just Goto Spring Initializer and create a new spring boot project in java 8 

##### Current Result
Continues Finding project and couldn't creating launch.json

##### Expected Result
Find Project and create lanuch.json
![Screenshot 2021-03-12 123851](https://user-images.githubusercontent.com/25478188/112439173-ccfd3f80-8d6e-11eb-86d0-dc810512f9fb.png)
![Screenshot 2021-03-25 133354](https://user-images.githubusercontent.com/25478188/112439177-ce2e6c80-8d6e-11eb-9b15-2bae6bc081a3.png)

**Comment by an-tho-ny** [comment]
I am having the same problem.
**Environment**
- Windows 10 Pro
- JDK version: 8
- VS Code version: 1.54.3
- Java Extension Pack: v0.13.0
- Spring Boot Dashboard: v0.2.0
- Spring Boot Tools: v1.25.0

![imagen](https://user-images.githubusercontent.com/74874159/112757303-836c5900-8fe9-11eb-97d3-b57f5822ff5f.png)

**Comment by Eskibear** [comment]
See: https://github.com/spring-projects/sts4/issues/612#issuecomment-802798311

**Comment by naveenroy001** [comment]
> See: [spring-projects/sts4#612 (comment)](https://github.com/spring-projects/sts4/issues/612#issuecomment-802798311)

Thanks @Eskibear
