### ISSUE TITLE
When running app, it shows old "main" classes

### ISSUE THREAD

**Issue by johnchesser** [microsoft/vscode-spring-boot-dashboard#134]
This plugin has been working great for me, but I have found something cosmetic that is causing me an extra click.

When I am developing a project it sometimes goes through various refactors.  Sometimes I change the location of the main method (package) or rename the class.  The spring boot dashboard seems to remember these old "invalid" locations and causes it to have a pop up at the top of the screen.

![image](https://user-images.githubusercontent.com/6753280/117675377-1e705b00-b172-11eb-9934-fab0faa2fd5b.png)

The top one is valid, the bottom two are invalid... but it would be great if the bottom two weren't there so there wouldn't be a pop up.

~~To work around this I can reimport the project into vscode (pretty sure that works).~~

(Ok, I just re-imported via remove folder from workspace and add folder etc, and it still shows the 3 entries

**Comment by larissarodr** [comment]
Same thing happening here.

**Comment by Eskibear** [comment]
Information of main class is queried from Java language server, not maintained by this extension. I just tried a) rename b) move into another package, but failed to reproduce.

How do you rename / move the class?
When it happens, can you check whether old classes are also revealed in "Java Projects" explorer? (It visualizes information in Java lanaguage server)

**Comment by johnchesser** [comment]
Just one more thing to add in.  If I remove project A from my workspace, and then I run project B, it still shows the 3 entries from projects A and B after I click the play button.  So I think they are "attached" to this project in some way.

If I refactor the main classes in either A or B it does the correct thing (old name becomes new name, but just for the good entry).

If nothing rings any bells or we can't duplicate I think I can spend some time building a clean case or getting it over to the Java Language Server section.

**Comment by johnchesser** [comment]
ok...........

A clean java language server workspace fixes it.  Any idea how I can report this intelligently?

**Comment by Eskibear** [comment]
Adding @jdneo @testforstephen for awareness. There can be potential inconsistency about main classes information.

**Comment by johnchesser** [comment]
I may be able to duplicate if necessary from scratch, just know that we do alot of copy / pasting / refactoring across projects and use a workspace with multiple projects in it.  We may also remove an reimport the same name of project that was from a different repository (code moved from one git repository to another).

**Comment by Eskibear** [comment]
Probably related to https://github.com/microsoft/vscode-java-debug/issues/1098 , hopefully it will be fixed automatically after we ship the fix in java-debugger extension.

**Comment by Eskibear** [comment]
already fixed in upstream.
