### ISSUE TITLE
How to read .env file when start spring boot app?

### ISSUE THREAD

**Issue by doggy8088** [microsoft/vscode-spring-boot-dashboard#140]
In my project, I don't have to define an `launch.json` file to start an app. Just hit `F5`, then app is running.

I'd like to use my own `.env` file, but I don't know how to setup. There is no docs about how to define a `launch.json` file when using Spring Boot Dashboard.

**Comment by doggy8088** [comment]
This is my workaround for this issue.

```sh
{
    "configurations": [
        {
            "type": "java",
            "request": "launch",
            "name": "Launch Spring Boot",
            "mainClass": "${workspaceFolder}/src/main/java/com/example/demo1/Demo1Application.java",
            "envFile": "${workspaceFolder}/.env"
        }
    ]
}
```

Is it possible Spring Boot Dashboard launch my app using this launch profile by default?

**Comment by Eskibear** [comment]
this extension picks existing launch configuration, if all these matche: type, request, mainClass, projectName. 

https://github.com/microsoft/vscode-spring-boot-dashboard/blob/97db7c9e36356709cecb180e2ca3116da6e7866f/src/Controller.ts#L179

**Comment by doggy8088** [comment]
@Eskibear I actually can Start app even I don't have a `launch.json` file in my project.

**Comment by Eskibear** [comment]
> just hit F5 key

I assume that you hit F5 with you main Java class file opened. That's because Java Debugger Extension automatically detected main classes for you, and launched a debug session with a temp config. In that case, of cause envFile was not specified because Java Debugger didn't have the knowledge.

**Comment by doggy8088** [comment]
I think you are right. No matter what I have to write my own `launch.json` to reading `.env` file for now.

I'm just curious that is it possible Spring Boot Dashboard launch my app using default launch profile if there is no `launch.json` defined?

**Comment by Eskibear** [comment]
> is it possible Spring Boot Dashboard launch my app using default launch profile if there is no launch.json defined?

It's actually doing so. If there's no `launch.json` file, it creates a default one for you, as below:
https://github.com/microsoft/vscode-spring-boot-dashboard/blob/97db7c9e36356709cecb180e2ca3116da6e7866f/src/Controller.ts#L191-L201

**Comment by doggy8088** [comment]
@Eskibear Wow, cool! Can I send a PR add `"envFile": "${workspaceFolder}/.env"` to this?

**Comment by Eskibear** [comment]
PR is welcome. 

I just have two questions before that,
- Is it a convention to use `.env` as envFile? If true or it's widely accepted, I'm ok with the change.
- What if `.env` doesn't exist under my workspace folder? We must ensure there's no regression for these users.

**Comment by doggy8088** [comment]
Answering your two questions:

1. Yes, the `.env` file is commonly used for many area including [Docker](https://docs.docker.com/compose/env-file/), [Docker Compose](https://docs.docker.com/compose/environment-variables/), [AIX](https://www.ibm.com/docs/en/aix/7.2?topic=files-env-file), [Node.js](https://www.npmjs.com/package/dotenv#rules). Also, IntellJ also have a popular plugin called [EnvFile](https://plugins.jetbrains.com/plugin/7861-envfile) do the same thing. It's a convention for sure.
2. If there is no `.env` file exist, nothing will be affected.
