### ISSUE TITLE
Add a link to GitHub repo

### ISSUE THREAD

**Issue by doggy8088** [microsoft/vscode-spring-boot-dashboard#143]
Could you add [VSCode Marketplace link of this extension](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-spring-boot-dashboard) to the GitHub Repo's About area?

Something like this:

![image](https://user-images.githubusercontent.com/88981/129224290-fa44d9d9-1337-40f3-92d6-d34119fe5998.png)

**Comment by Eskibear** [comment]
added
