### ISSUE TITLE
Run microservice with profile in VS Code

### ISSUE THREAD

**Issue by martinlippert** [microsoft/vscode-spring-boot-dashboard#145]
There is an enhancement request filed against the STS4 repo that really belongs to the boot dashboard project in VSCode, therefore adding this item here... :-)

The detailed description is here:
https://github.com/spring-projects/sts4/issues/678

**Comment by Eskibear** [comment]
implemented. see https://github.com/microsoft/vscode-spring-boot-dashboard/pull/309#issuecomment-1499866377
