### ISSUE TITLE
Couldn't determine port app is running on

### ISSUE THREAD

**Issue by TomaszPiec** [microsoft/vscode-spring-boot-dashboard#150]
After running simple spring boot application I am unable to use button "open in Browser". Instead of opening application I see error : "Couldn't determine port app is running on"

![image](https://user-images.githubusercontent.com/34058616/141793179-c649356c-858a-4ff5-9bba-5e7db28778a9.png)

Is there any configuration missing?
Is there any dependency missing?

**Comment by Eskibear** [comment]
It failed to read corresponding `port` via JMX. Can you provide the "simple boot application"?

See below: 
https://github.com/microsoft/vscode-spring-boot-dashboard/blob/9bf091576e5a640bf5caa755e6374ddab2cd5f71/src/Controller.ts#L133-L140

https://github.com/microsoft/vscode-spring-boot-dashboard/blob/9bf091576e5a640bf5caa755e6374ddab2cd5f71/java-extension/src/main/java/com/microsoft/vscode/spring/boot/dashboard/java/extension/JmxService.java#L36-L42
