### ISSUE TITLE
Visualize beans / API endpoints

### ISSUE THREAD

**Issue by Eskibear** [microsoft/vscode-spring-boot-dashboard#164]
Goals:
- Provide diagrams of beans of Spring applications (along with bean's dependency)
- Provide diagrams of REST API endpoints / mappings of Spring applications
- Provide both live and static information of the diagrams mentioned above

Actions to take:
- Static information
  - fetch symbols from spring-tools extension or directly parse the project?
    - https://github.com/microsoft/vscode-spring-boot-dashboard/pull/171
    - https://github.com/microsoft/vscode-spring-boot-dashboard/pull/172
- Live process data 
  - Beans
    - [x] list beans
    - [x] navigate to target class
      - https://github.com/microsoft/vscode-spring-boot-dashboard/commit/16e7a68f626daa25050407fed5779875d4c6add4
    - [x] show dependencies
  - Mappings
    - [x] list mappings
    - [x] shortcut to open endpoint
      - https://github.com/microsoft/vscode-spring-boot-dashboard/pull/165 
    - [x] navigate to definition

**Comment by Eskibear** [comment]
So far we can show beans/endpoint mappings in vscode, below use cases are supported. You can verify them in pre-release channel.

1. Open a springboot project, beans and endpoints defined in your project should show in corresponding tree view.
2. You can navigate to the definition by left-click on the tree item.
3. From dashboard, you can run/debug your project, live connection should be automatically connected, and beans/endpoints view should show data from live connection now. Color of the icons will change to green indicating that.
4. When live data is showing, by click on swtich buttons in view title, you can switch between "defined" and "all" beans/mappings.
5. For Get endpoints, there's inline button which opens corresponding requests in integrated browser.
6. In any case the live connections is disconnected (e.g. you stop debugging or terminate the process), dashboard changes back to show static data.


Note that, visualization of bean dependencies would be implemented later with reference view.

**Comment by CsCherrYY** [comment]
> For Get endpoints, there's inline button which opens corresponding requests in integrated browser.

The codelens will open a system browser instead of an integrated browser? can we also open it in the integrated browser?
![image](https://user-images.githubusercontent.com/45906942/171341303-65cfa168-5ccb-4935-963f-b03c710dab6e.png)

**Comment by Eskibear** [comment]
> can we also open it in the integrated browser

No for the moment. It's implemented in spring-tools ext. I can init a PR upstream.

**Comment by CsCherrYY** [comment]
> You can navigate to the definition by left-click on the tree item.

for bean `crashController` in project spring-petclinic, if you navigate to the definition
- in the static mode (app not running), the editor will jump to the annotation (CrashController.java:28)
- when app is running, the editor will jump to the class (CrashController.java:29)

is this behavior by design?

**Comment by Eskibear** [comment]
I find a bug with redhat.java@universal, where no tooling jre embedded. See #174
