### ISSUE TITLE
Spring Boot Dashboard only displays in Spring

### ISSUE THREAD

**Issue by mnmpeterson** [microsoft/vscode-spring-boot-dashboard#176]
Spring Boot Dashboard view used to show in the Explorer view.  It somehow disappeared and when I open the view, it shows it will only display in Side Bar/Spring.  How do I get it to display in the Explorer again?
![image](https://user-images.githubusercontent.com/14947436/171485977-07ea81b2-2b1f-463e-9da4-d3a3a7b7370f.png)

**Comment by Eskibear** [comment]
You can drag and drop it to the target location.

**Comment by Eskibear** [comment]
Closing. let me know if it's still not working for you.
