### ISSUE TITLE
Support URLs starting with https for the open actions

### ISSUE THREAD

**Issue by duoduobingbing** [microsoft/vscode-spring-boot-dashboard#182]
I have a Spring Boot App with HTTPS enabled.

![examoke](https://user-images.githubusercontent.com/50800372/173206076-54b400a6-92e5-485e-9897-558569f802bc.PNG)

The top button by default tries to open `http://localhost:8090/example` which of course does not work. Setting `"spring.dashboard.openUrl": "https://localhost:{port}{contextPath}/"` in `.vscode/settings.json` solves that.

The main problem is that the lower panel
![Screenshot (3)](https://user-images.githubusercontent.com/50800372/173206208-ec27ef4c-e974-4a8b-aade-997c33562347.png)
does not respect setting this property. It still tries to open `http://localhost:8090/example` instead of `https://localhost:8090/example`.

It would be nice if the open buttons in the lower panel respected the property as well.

**Comment by Eskibear** [comment]
@duoduobingbing Please try latest pre-release, let me know if that works.

**Comment by Eskibear** [comment]
I'm thinking of whether we can infer 'http' or 'https' as the protocol. Do we have any env/variable indicating that?

**Comment by duoduobingbing** [comment]
> @duoduobingbing Please try latest pre-release, let me know if that works.

Sorry for taking so long to reply. It works like a charm now; thanks for fixing this so swiftly.
