### ISSUE TITLE
Custom annotations shown as null in Beans Tab

### ISSUE THREAD

**Issue by cedbesafilm** [microsoft/vscode-spring-boot-dashboard#207]
Once a custom annotation has been created, it is added to the BEANS tab (since it contains the @Component annotation) but is displayed as null in the list

```
@Target({ElementType.TYPE})
@Retention(RetentionPolicy.RUNTIME)
@Documented
@Component
public @interface PersistenceAdapter {

  @AliasFor(annotation = Component.class)
  String value() default "";

}
```
![image](https://user-images.githubusercontent.com/55377336/186357759-8a3ee0df-2d63-4d2e-841c-3c7967355723.png)

**Comment by Eskibear** [comment]
I can reproduce. 

![image](https://user-images.githubusercontent.com/2351748/186364423-f8c3846f-060d-4a0f-afc9-f04cbd1368b1.png)

When your app is not running, static beans/endpoints are parsed from workspace symbols. And the information is from upstream extension [vscode-spring-boot](https://github.com/spring-projects/sts4/tree/main/vscode-extensions/vscode-spring-boot). 

Can you help to create an issue there, and link it to this one?

**Comment by Eskibear** [comment]
fixed in upstream
