### ISSUE TITLE
Allow for the overriding of default plugin-set vmArgs

### ISSUE THREAD

**Issue by tkah** [microsoft/vscode-spring-boot-dashboard#222]
We are getting dinged from our company IT for our team's machines throwing "Java JMX Agent Insecure Configuration" errors during security scans. I believe it may be because of our use of this plugin. I have tried to disable JMX outright via the vmArgs in our `local.json` even though I know this will impact the performance of the plugin. However, I believe my argument is being overridden by the argument added in #93 . I see there is a TODO marked on line [73](https://github.com/Eskibear/vscode-spring-boot-dashboard/blob/6c631319df768addcd716e6f2455f7e485140c07/src/Controller.ts#L73) of the impacted file to merge args differently.

Could arguments be processed to favor user arguments over those set by the plugin?

Thanks.

**Comment by Eskibear** [comment]
It makes sense no to override user-defined vmargs. 

I guess the insecure warning is from below vmargs, with which we used to fetch server.port and contextPath of the running apps.

https://github.com/microsoft/vscode-spring-boot-dashboard/blob/0dfbb122aa7cb44aa0a2f69f7352f28a928ffb44/src/Controller.ts#L73-L76

Not sure whether below vm args works with your company policy, but they are critical to most features... Now they are also added by upstream extension, so probably we can also remove them. See https://github.com/spring-projects/sts4/blob/01008b3375ab8aabaa7dba18bbe72eca9e298f55/vscode-extensions/vscode-spring-boot/lib/debug-config-provider.ts#L15-L35

https://github.com/microsoft/vscode-spring-boot-dashboard/blob/0dfbb122aa7cb44aa0a2f69f7352f28a928ffb44/src/Controller.ts#L77-L80

**Comment by tkah** [comment]
I agree. I'm not arguing to override user vmArgs, but to override the plugin args with user args. Maybe that's what is happening on line 73? I'm not sure of the order of precedence with regard to the command line arguments.

We specifically wanted to set `'-Dspring.jmx.enabled=false'` I know that this will cause issues with some of the plugin features, but we wanted to give it a try just to see if this was indeed the source of the issue we are getting.

But you're saying these settings don't matter anyway as they are overidden by those set in `debug-config-provider.ts`?

**Comment by Eskibear** [comment]
> as they are overidden by those set in debug-config-provider.ts?

Implementation in `debug-config-provider.ts` is less aggressive. It only adds those vmArgs when they are not explicitly specified by users. I.e. if you set `'-Dspring.jmx.enabled=false'`, it won't override it to `true`.

We can use the same mechanism to avoid being aggressive.
