### ISSUE TITLE
Dashboard is loading forever

### ISSUE THREAD

**Issue by izilongwan** [microsoft/vscode-spring-boot-dashboard#223]
![image](https://user-images.githubusercontent.com/48234072/192454982-24cb78d1-678b-44a1-9949-08650e0a39d4.png)
![image](https://user-images.githubusercontent.com/48234072/192455610-83743562-f4ce-470e-8e3f-dc641d783f10.png)
项目都启动不了

**Comment by Eskibear** [comment]
It depends on Java extension to be activated first. 

Can you provide a list of installed extensions and their versions? 

And tell us more about how you reproduce the issue.

**Comment by izilongwan** [comment]
> It depends on Java extension to be activated first.
> 
> Can you provide a list of installed extensions and their versions?
> 
> And tell us more about how you reproduce the issue.

![image](https://user-images.githubusercontent.com/48234072/192464738-61cff42c-e40a-4de9-9d07-19c98d17e828.png)
该有依赖我都装过了, 就是升级vscode后这个就一直卡在加载

**Comment by Eskibear** [comment]
> It depends on Java extension to be activated first.

You can run `Developer: Show Running Extensions` from command palette, see if Java extension is activated. Or open a .java file, see if there's a "thumb-up" icon in bottom right corner indicating it's ready. (while activating, it's a spinning "sync" icon).

> Can you provide a list of installed extensions and their versions?

Can you share the **VERSION** of Spring Boot Dashboard extension? 


And if possible, share a sample project and describe how you reproduce it. If it's private, describe the structure of your project, or find a way (or constuct a minimal sample project) to stably reproduce it. Otherwise it's hard to guess the root cause in blind.

**Comment by izilongwan** [comment]
> > It depends on Java extension to be activated first.
> 
> You can run `Developer: Show Running Extensions` from command palette, see if Java extension is activated. Or open a .java file, see if there's a "thumb-up" icon in bottom right corner indicating it's ready. (while activating, it's a spinning "sync" icon).
> 
> > Can you provide a list of installed extensions and their versions?
> 
> Can you share the **VERSION** of Spring Boot Dashboard extension?
> 
> And if possible, share a sample project and describe how you reproduce it. If it's private, describe the structure of your project, or find a way (or constuct a minimal sample project) to stably reproduce it. Otherwise it's hard to guess the root cause in blin

> > It depends on Java extension to be activated first.
> 
> You can run `Developer: Show Running Extensions` from command palette, see if Java extension is activated. Or open a .java file, see if there's a "thumb-up" icon in bottom right corner indicating it's ready. (while activating, it's a spinning "sync" icon).
> 
> > Can you provide a list of installed extensions and their versions?
> 
> Can you share the **VERSION** of Spring Boot Dashboard extension?
> 
> And if possible, share a sample project and describe how you reproduce it. If it's private, describe the structure of your project, or find a way (or constuct a minimal sample project) to stably reproduce it. Otherwise it's hard to guess the root cause in blind.

> > It depends on Java extension to be activated first.
> 
> You can run `Developer: Show Running Extensions` from command palette, see if Java extension is activated. Or open a .java file, see if there's a "thumb-up" icon in bottom right corner indicating it's ready. (while activating, it's a spinning "sync" icon).
> 
> > Can you provide a list of installed extensions and their versions?
> 
> Can you share the **VERSION** of Spring Boot Dashboard extension?
> 
> And if possible, share a sample project and describe how you reproduce it. If it's private, describe the structure of your project, or find a way (or constuct a minimal sample project) to stably reproduce it. Otherwise it's hard to guess the root cause in blind.

状态是ok的

> > It depends on Java extension to be activated first.
> 
> You can run `Developer: Show Running Extensions` from command palette, see if Java extension is activated. Or open a .java file, see if there's a "thumb-up" icon in bottom right corner indicating it's ready. (while activating, it's a spinning "sync" icon).
> 
> > Can you provide a list of installed extensions and their versions?
> 
> Can you share the **VERSION** of Spring Boot Dashboard extension?
> 
> And if possible, share a sample project and describe how you reproduce it. If it's private, describe the structure of your project, or find a way (or constuct a minimal sample project) to stably reproduce it. Otherwise it's hard to guess the root cause in blind.

状态是ok的

**Comment by izilongwan** [comment]
![image](https://user-images.githubusercontent.com/48234072/192469889-28b92b89-8d1b-45c2-9db1-a8e56e588012.png)
![image](https://user-images.githubusercontent.com/48234072/192469994-41d7f035-0e54-4a3c-b60d-27c28f97330e.png)

**Comment by izilongwan** [comment]
![image](https://user-images.githubusercontent.com/48234072/192470233-a2e29542-7bc6-4242-88b3-26b156ab9077.png)

**Comment by Eskibear** [comment]
No obvious clues. And I cannot reproduce with a couple of spring boot projects. 

You may check `Developer: Toggle Developer Tools`, in "Console" panel see if there's any related error.


> 该有依赖我都装过了, 就是升级vscode后这个就一直卡在加载
> I have installed all the dependencies, but after upgrading vscode, this has been stuck in loading

Or if you suspect something wired happened with vscode, you can try re-install vscode or the extensions. BTW the extensions are installed under `~.vscode/extensions/`  folder, you can clean it up and re-install them all.

**Comment by izilongwan** [comment]
![image](https://user-images.githubusercontent.com/48234072/192484656-df0e2937-a02b-4552-8aa8-c7996d721393.png)
![image](https://user-images.githubusercontent.com/48234072/192484941-577babc8-d7fd-4013-a502-013dc4af6d91.png)

控制台确实有报错的
