### ISSUE TITLE
Memory View: Apply vscode setting changes to existing connections and Plot the graph immediately when the view is loaded 

### ISSUE THREAD

**Issue by vudayani-vmw** [microsoft/vscode-spring-boot-dashboard#241]
Two UX follow-ups from [#239](https://github.com/microsoft/vscode-spring-boot-dashboard/pull/239#issuecomment-1313205616):

1. The memory view settings (max data points and interval) should be applied to live running processes

    The current behavior is that the changes to these settings are not effective immediately for a running process. The graph is 
    plotted with old intervals and max points values. The live process has to be re-run for the changes to be applied to the graph. 

   The expected behavior:
    - the changes to the settings should be applied to existing connections
    - any changes to the settings when the memory view is collapsed should also be applicable when the memory view is expanded

2. Plot the memory graph instead of showing an empty canvas when a live connection is established

   Currently, when a live process is connected, the memory view just shows the drop-downs. The graph is plotted after an initial 
   delay (interval configured in settings). During this interval, the memory view looks empty or broken.

   The expected behavior:
   - data is fetched immediately once the live process is connected
   - plot the graph without the initial delay when the memory view is loaded
   - subsequently, the graph is updated every "N" seconds, N being the interval configured in the settings

**Comment by Eskibear** [comment]
closed by #242
