### ISSUE TITLE
UX improvement of memory view

### ISSUE THREAD

**Issue by Eskibear** [microsoft/vscode-spring-boot-dashboard#245]
UX improvement.

<img width="342" alt="image" src="https://user-images.githubusercontent.com/2351748/202335717-63e510db-ff79-4b75-9ba7-ce24445ced6e.png">

With default layout, graph is not presented well in memory view, and you have to scroll to see it. To have the best practice you have to increase width of sidebar.
I think we can make more use of the visual space of memory view, with below suggestions:
- place the two drop-downs into the same row, and maybe put at the bottom, below the graph.
- adjust size of legend/labels of the graph, to **show more about the plot part**.
- better to make the page **responsive**, i.e., especially when width is small, currently it's not much helpful, as below.

<img width="283" alt="image" src="https://user-images.githubusercontent.com/2351748/202337138-9c2886b9-3576-4a8a-8571-7fe105fc50bd.png">

_Originally posted by @Eskibear in https://github.com/microsoft/vscode-spring-boot-dashboard/issues/242#issuecomment-1317956354_

**Comment by Eskibear** [comment]
@vudayani-vmw

**Comment by vudayani-vmw** [comment]
@Eskibear 

This PR https://github.com/microsoft/vscode-spring-boot-dashboard/pull/251 is a first step towards improving the UX for memory view.
I have moved the dropdowns below the graph and tried to adjust the graph layout for smaller width cases.

Having the dropdowns in the same row squashes the process name field. It is difficult to identify a process when multiple processes are running. 

<img width="272" alt="image" src="https://user-images.githubusercontent.com/79973862/203292780-161dd919-ecf7-4ec2-ad98-474072851bb2.png">

**Comment by Eskibear** [comment]
> It is difficult to identify a process when multiple processes are running.

Agree. Then let's keep the dropdowns as they are for now. 

BTW, one idea is, can we make the process identifier more user-friendly. E.g. Given the assumption that process name for local live process is full qualified name of the main class, how about showing name of corresponding project instead of full qualified name. `appsProvider.manager.getAppByMainClass(mainClassName)` returns the corresponding BootApp if exists.
