### ISSUE TITLE
When line wrapping is enabled, editor code alignment lines are messed up.

### ISSUE THREAD

**Issue by zhouxinghong** [microsoft/vscode-spring-boot-dashboard#257]
Type: <b>Bug</b>

When line wrapping is enabled, editor code alignment lines are messed up.
vscode:1.74
Spring Boot Dashboard: 0.9.0
jdk: 11
Windows10: 2022H2

Extension version: 0.9.0
VS Code version: Code 1.74.0 (5235c6bb189b60b01b1f49062f4ffa42384f8c91, 2022-12-05T16:38:16.075Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

![2022-12-13_094047-2](https://user-images.githubusercontent.com/54253524/207206211-1172ad52-2a9f-4025-b964-a7a9166119d2.png)

![2022-12-13_093614](https://user-images.githubusercontent.com/54253524/207205866-29ec126a-3854-478d-ac54-0b3e6bf7a2ce.png)

**Comment by Eskibear** [comment]
turn it off via setting `spring.dashboard.enableGutter` to unblock yourself.

**Comment by zhouxinghong** [comment]
Now that it is confirmed to be a bug, please fix it and publish it as soon as possible, thank you!
This setting spring.dashboard.enableGutter should be ignored.

**Comment by zhouxinghong** [comment]
> turn it off via setting `spring.dashboard.enableGutter` to unblock yourself.

Now that it is confirmed to be a bug, please fix it and publish it as soon as possible, thank you!
This setting spring.dashboard.enableGutter should be ignored.

**Comment by Eskibear** [comment]
We decorate each line with either a "gutter icon" or a "blank placeholder" at the beginning, using vscode's API. The vertical lines are rendered by vscode itself. So when you turn line wrapping on, without the "placeholder", the vertical lines are not aligned.
AFAIK, I cannot fix it with currently available APIs. I marked it as `upstream` and this should be discussed in vscode's repo.

**Comment by Eskibear** [comment]
should be fixed by #291 . Try it in tomorrow's pre-release.
