### ISSUE TITLE
add support to select spring profile to use for executing app

### ISSUE THREAD

**Issue by gayanper** [microsoft/vscode-spring-boot-dashboard#263]
add support to select spring profile to use for executing app when there are profiles define for a spring boot app.

**Comment by dev117uday** [comment]
setting profiles as an option in Spring Boot Dashboard would be great to have feature as sometimes its needed to switch btw multiple profiles

**Comment by Eskibear** [comment]
implemented. see https://github.com/microsoft/vscode-spring-boot-dashboard/pull/309#issuecomment-1499866377

**Comment by Eskibear** [comment]
@gayanper 
yes, it should work after updating this regexp to also include `yml`, as I mentioned in https://github.com/microsoft/vscode-spring-boot-dashboard/pull/309#issuecomment-1538290697
