### ISSUE TITLE
dashboard only loads symbols for first project that is opened in a multi-module workspace

### ISSUE THREAD

**Issue by gayanper** [microsoft/vscode-spring-boot-dashboard#264]
when opening a workspace with multi module the dashboard only loads symbols such as beans, endpoints only for one project which is most of the time where a project file was opening such as a java file.

but all symbols are available when searching for them in GoTo command.

**Comment by Eskibear** [comment]
I cannot reproduce it. Can you provide a sample project and describe how you open it?

Below is a screenshot that I opened a multi module project from https://github.com/deepaksrivastav/spring-boot-multimodule
Beans/endpoints are well listed under corresponding modules...

![image](https://user-images.githubusercontent.com/2351748/218913962-4b6e75fa-fa07-496e-b6f0-2d203a8ef5c1.png)
