### ISSUE TITLE
Doesn't work with Spring Boot Tools v1.44.0

### ISSUE THREAD

**Issue by TanyaMio** [microsoft/vscode-spring-boot-dashboard#270]
After updating Spring Boot Tools extension to the newest 1.44.0 version - kept showing this error message:
```
Cannot activate the 'Spring Boot Dashboard' extension because it depends on an unknown 'Pivotal.vscode-spring-boot' extension.
```

If I revert Spring Boot Tools back to 1.43.0 - everything works.

**Comment by Eskibear** [comment]
Upstream extension has changed its publisher id from `Pivotal` to `vmware`. Will ship a fix soon. See #271
