### ISSUE TITLE
Not compatible with Spring Boot Tools 1.44, still linking to the old id from pivotal

### ISSUE THREAD

**Issue by Super169** [microsoft/vscode-spring-boot-dashboard#273]
The following error is prompted when starting  Spring Boot Dashboard :
Cannot activate the 'Spring Boot Dashboard' extension because it depends on an unknown 'Pivotal.vscode-spring-boot' extension.

In fact, there has similar issue for newly installed machine as the Spring Boot Dashboard has not include Spring Boot Tools (already because it still linked to old version with id Pivotal.vscode-spring-boot). But it still compatible in 1.43, so it still work if we install Spring Boot Tool manually. But for 1.44, it cannot start anymore.

Please update the reference to new id :  vmware.vscode-spring-boot

**Comment by Eskibear** [comment]
duplicated with #270 . 

Please try dashboard extension v0.10.1, which was released a few minutes ago.
