### ISSUE TITLE
Error: Failed to register classpath listener after 10 retries.

### ISSUE THREAD

**Issue by MajorTomMan** [microsoft/vscode-spring-boot-dashboard#279]
When I open the springboot dashboard, nothing appears
![image](https://user-images.githubusercontent.com/47267913/220369587-b3ea49d3-b4b1-487a-9da6-55637586d5b1.png)
 and the console gives me the following error
![image](https://user-images.githubusercontent.com/47267913/220371608-4a1511ff-72c7-438b-894a-5a0cf6dc9f23.png)
pls fix it.......
My environment is as follows
openjdk version "17.0.5" 2022-10-18
OpenJDK Runtime Environment (build 17.0.5+8-Ubuntu-2ubuntu120.04)
OpenJDK 64-Bit Server VM (build 17.0.5+8-Ubuntu-2ubuntu120.04, mixed mode, sharing)
Plugin versions are as follows
Spring Boot DashBoard version is v0.10.1
Spring Boot Tools version is 1.44.0-RC.2

**Comment by Eskibear** [comment]
Might be regression from upstream, under investigation. You can downgrade your Java extension (Language Support for Java by Red Hat) to 1.14.0. Give it a try and let me know if it mitigates the issue.

**Comment by MajorTomMan** [comment]
> Might be regression from upstream, under investigation. You can downgrade your Java extension (Language Support for Java by Red Hat) to 1.14.0. Give it a try and let me know if it mitigates the issue.

no,it is still not working and still report same error....
![image](https://user-images.githubusercontent.com/47267913/220400800-4ae7b2c8-5eab-452b-87bd-fe0e47afc299.png)
here is error report
![image](https://user-images.githubusercontent.com/47267913/220401062-e5e79215-f688-4199-9e23-7c05605e3035.png)
and for some reason,spring dashboard  dont have any output
![image](https://user-images.githubusercontent.com/47267913/220401304-03813938-7e46-4706-a053-42732373e3b5.png)

**Comment by Eskibear** [comment]
Something wrong with executing upstream commands. However, the original error was swallowed...

https://github.com/microsoft/vscode-spring-boot-dashboard/blob/ec9a9dd2545c2360747fded9fe7b87a22881534c/src/BootAppManager.ts#L122-L132

You may print the raw error message by manually modifying the extension code installed on your machine. Following:
- open file `~/.vscode/extensions/vscjava.vscode-spring-boot-dashboard-<version>/out/src/BootAppManager.js`
- add `console.warn(error);` in the "catch" block as I quoted above.
- reload the window to make it effective.
- then you'll see the raw error there in console.

**Comment by MajorTomMan** [comment]
so here is raw error i got
![image](https://user-images.githubusercontent.com/47267913/220508023-fbe5cbed-c0a7-4d70-9e03-87d9669246da.png)

**Comment by MajorTomMan** [comment]
> Something wrong with executing upstream commands. However, the original error was swallowed...
> 
> https://github.com/microsoft/vscode-spring-boot-dashboard/blob/ec9a9dd2545c2360747fded9fe7b87a22881534c/src/BootAppManager.ts#L122-L132
> 
> You may print the raw error message by manually modifying the extension code installed on your machine. Following:
> 
> * open file `~/.vscode/extensions/vscjava.vscode-spring-boot-dashboard-<version>/out/src/BootAppManager.js`
> * add `console.warn(error);` in the "catch" block as I quoted above.
> * reload the window to make it effective.
> * then you'll see the raw error there in console.

so here is raw error i got
![image](https://user-images.githubusercontent.com/47267913/220508244-fdeb5c23-4512-49a6-96ad-569bdd6b0178.png)

**Comment by Eskibear** [comment]
I don't see any related. Is there any other message in yellow background? 

From current messages I guess probably Java extension is not ready yet. To verify, you can expand "Java Projects" view, check if your projects are properly listed there. 

BTW, it seems that you are using vscode-remote extension. Or can you provide a sample project and describe how you open it?

**Comment by MajorTomMan** [comment]
That's strange. It looks like this error only happens when running the Vscode extension on WSL remotely. When I run vscode on my local host, Spring and SpringBoot extensions work fine, but the Vscode console on WSL reports the error posted earlier, while Java Projects in vscode running on WSl is displayed normally

**Comment by MajorTomMan** [comment]
> I don't see any related. Is there any other message in yellow background?
> 
> From current messages I guess probably Java extension is not ready yet. To verify, you can expand "Java Projects" view, check if your projects are properly listed there.
> 
> BTW, it seems that you are using vscode-remote extension. Or can you provide a sample project and describe how you open it?

That's strange. It looks like this error only happens when running the Vscode extension on WSL remotely. When I run vscode on my local host, Spring and SpringBoot extensions work fine, but the Vscode console on WSL reports the error posted earlier, while Java Projects in vscode running on WSl is displayed normally

**Comment by Eskibear** [comment]
No idea what happened yet. I just tried opening a spring-petclinic project on WSL, and everything worked fine. Maybe you can try thoroughly removing and re-installing the extensions on WSL, which is located under `~/.vscode-server`.

**Comment by MajorTomMan** [comment]
> No idea what happened yet. I just tried opening a spring-petclinic project on WSL, and everything worked fine. Maybe you can try thoroughly removing and re-installing the extensions on WSL, which is located under `~/.vscode-server`.

Still not working I've reinstalled Java and Spring extensions on WSL

**Comment by MajorTomMan** [comment]
> No idea what happened yet. I just tried opening a spring-petclinic project on WSL, and everything worked fine. Maybe you can try thoroughly removing and re-installing the extensions on WSL, which is located under `~/.vscode-server`.

this bug was fixed by spring boot tools,so thx for help

**Comment by Eskibear** [comment]
Good to know that. Can you point me to the corresponding commit or issue in spring boot tools?

**Comment by MajorTomMan** [comment]
> Good to know that. Can you point me to the corresponding commit or issue in spring boot tools?

no problem
here is issue link 
https://github.com/spring-projects/sts4/issues/982#issue-1598923019
good luck

**Comment by Eskibear** [comment]
Thank you! I'm closing it now.
