### ISSUE TITLE
Allow selecting multiple boot apps at once and... starting / stopping then together

### ISSUE THREAD

**Issue by kdvolder** [Microsoft/vscode-spring-boot-dashboard#28]
This is to support use case where I have multiple apps (microservices) meant to work together. I want to be able to start them all with a 'single click'.

In STS/Eclipse version of the boot dash this is supported by allowing multiple apps to be selected. Then using the start / stop / debug actions will operate on all the selected apps.

**Comment by Eskibear** [comment]
It is blocked by VS Code tree view APIs. But I can think of some alternative ways:
a. Add a command `start-multiple-apps`, it drops down a list of apps, so I can choose some of them to start. 

OR

b. Add a command `start-all-apps`, it simple starts all the apps in your workspace (as they are probably supposed to be a whole project). But this seems to be too aggressive.

**Comment by Eskibear** [comment]
[Multiple Debug Consoles](https://code.visualstudio.com/updates/v1_29#_multiple-debug-consoles) is supported in VS Code 1.29.0, now output of different apps will be redirected to different debug console.

![image](https://user-images.githubusercontent.com/2351748/48393050-f04c6480-e748-11e8-80ca-cb1ee4c5e26f.png)

So I think we can now support the following command for convenience and better UX.  

> a. Add a command start-multiple-apps, it drops down a list of apps, so I can choose some of them to start.

**Comment by Eskibear** [comment]
It looks like: 

![dashboard-start-multi](https://user-images.githubusercontent.com/2351748/48396123-60141c80-e754-11e8-8448-615300f0d01e.gif)
