### ISSUE TITLE
Extension uses different compiler

### ISSUE THREAD

**Issue by dawosch** [microsoft/vscode-spring-boot-dashboard#296]
Hey, i'm using visual studio code with the "extension pack for java" extension.
Local i have installed java 17 (microsoft edition).
When i build my project with `mvn -U clean install` there will be classes generated and everything is fine.
But then when i want to start my project with the spring boot dashboard extension my project will also compiled but with a different compiler. And i don't know where this compiler comes from.

Here is one file compiled with maven:
![image](https://user-images.githubusercontent.com/57100280/226126365-9e61d38e-d44d-4186-a212-37c15522eb41.png)

And here is the same file after starting the project from the extension:
![image](https://user-images.githubusercontent.com/57100280/226126389-60c8efcd-5570-45e7-a740-51a11851f37b.png)

Have a look at line 20.

Here is a repository i created to reproduce the error: [Repository](https://github.com/dawosch/vscode-java-extension-compiler-error)

Do you know how to solve this problem and why this happens?

**Comment by Eskibear** [comment]
Dashboard eventually depends on Java extension to compile the projects. And the intellisense like highlighting/diagnostics/navigation etc are all based on that. See https://github.com/redhat-developer/vscode-java

> java.autobuild.enabled : Enable/disable the 'auto build'.

For the moment AFAIK, you may manually turn off the "Auto build" of that compiler. Then it probably won't overwrite the classes you generated by mvn command.

cc @testforstephen @jdneo for awareness.

**Comment by dawosch** [comment]
Hey thanks for your answer.
The auto build setting is turned off.
But this setting will be ignored by the java debug setting:
![image](https://user-images.githubusercontent.com/57100280/226157293-8501abbc-be31-449c-b7a6-6a3745588474.png)

**Comment by Eskibear** [comment]
Then you might also turn the debug setting off. //cc the maintainer @testforstephen for awareness.

**Comment by dawosch** [comment]
You mean the setting of my post before?
That's the point. I can't set it to off, because when auto build is false the force build before launch setting ignores its value and compiles anyway.
![image](https://user-images.githubusercontent.com/57100280/226163969-7541fa88-7f9d-4998-8f17-6628fde7c4b4.png)

My code will be compiled anyway with this eclipse compiler.

**Comment by Eskibear** [comment]
I was wrong about the debugger setting mentioned above. Now I get the point. 

It looks like Java debugger requires output from eclipse compiler to run your projects. It's somehow reasonable to me, because otherwise it has no knowledge of the classpaths and main class to run.

But I'm not an expert, I'll invite @testforstephen , see if we can unblock your use case.

**Comment by dawosch** [comment]
Like always, if you talk about it your brain starts working.
It's defenetivly a problem with the readhat vscode-java extension.

Instead of running the app over the spring dashboard extension, the error occurs also if you press shift alt b on the project which starts the compiler.
And this is a shortcut added by the redhat extension.
I will try my luck there :)

Thanks a lot, maybe you will find a workaround first.

**Comment by testforstephen** [comment]
You can turn off autobuild settings, then choose to use maven command to launch your springboot app, and attach it to Java Debugger.

In `.vscode/tasks.json`:
```json
{
	"version": "2.0.0",
	"tasks": [
		{
            "label": "mvnDebug",
            "type": "shell",
            "command": "mvn spring-boot:run -Dspring-boot.run.jvmArguments=\"-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=5005\"",
            "isBackground": true,
            "problemMatcher": [{
                "pattern": [{
                    "regexp": "\\b\\B",
                    "file": 1,
                    "location": 2,
                    "message": 3
                }],
                "background": {
                    "activeOnStart": true,
                    "beginsPattern": "^.*Preparing to execute Maven in debug mode.*",
                    "endsPattern": "^.*Listening for transport dt_socket at address.*"
                }
            }]
        }
	]
}
```

In `.vscode/launch.json`:
```json
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "java",
            "name": "Attach",
            "request": "attach",
            "hostName": "localhost",
            "port": 5005,
            "projectName": "", // the target project name,
            "preLaunchTask": "mvnDebug"
        }
    ]
}
```

And run debugger via the new launch config:
![image](https://user-images.githubusercontent.com/14052197/226235708-7e0544a5-0d4c-4d84-b0c7-041f31c90384.png)
