### ISSUE TITLE
Endpoint URLs should be mapped correctly in Codespaces

### ISSUE THREAD

**Issue by akaroml** [microsoft/vscode-spring-boot-dashboard#300]
The URLs all use ```localhost``` as the host. But these types of URLs are not accessible to users using a remote environment like Codespaces. To make this correct, the dashboard extension needs to:
1. Be aware of the current environment
2. Generate URLs using the correct host and make sure they are accessible with a single click
3. Check if the required port is forwarded and ask if not

**Comment by Eskibear** [comment]
Demo of PR #301 

https://user-images.githubusercontent.com/2351748/228149773-606f6ecd-3bbc-4cae-89a9-c14d31bc8ffb.mp4
