### ISSUE TITLE
Show active profiles on BootApp description when attached to live process

### ISSUE THREAD

**Issue by karthik20** [microsoft/vscode-spring-boot-dashboard#320]
### At Present:
Spring boot dashboard doesn't show the active profiles loaded for the app on startup - only **port** is available in app description when actuator is on.

### Suggested improvement:
It would be useful to show how the app has been started and on which **profiles** that were selected in the dialog without the need to look into the logs.

**Planning to show the description with profiles as follows:**

**_When profiles were selected:_** 
**Option 1: without braces (with all description):**

![image](https://github.com/microsoft/vscode-spring-boot-dashboard/assets/12153250/8cfb4f5c-a21c-4dff-b0a2-f70be690c239)

**_When no profiles were selected:_** 

![image](https://github.com/microsoft/vscode-spring-boot-dashboard/assets/12153250/271abb51-4c6d-4c12-81f6-e8f0d7ae7455)

I did some changes to achieve this. If this sounds like a valid improvement, I can submit a PR for the same.

**Comment by BoykoAlex** [comment]
@martinlippert my only suggestion for the PR try to use active profiles from live data if it is available. Also a command on the Boot LS side providing a list of available profiles would be very useful (i.e. to cover single property files with multiple documents)

**Comment by karthik20** [comment]
@BoykoAlex  Do we have any nightly builds for this extension? There have not been any releases for an year and has been in preview state as well. Would be great if we can have nighly builds and/or frequent releases.

**Comment by BoykoAlex** [comment]
I've tried the pre-release version and didn't see the profile showing. @testforstephen do you know if pre-release should have the change?

**Comment by testforstephen** [comment]
Spring Boot Dashboard pre-release version 0.13.2024042402 is released today, pls try again.

**Comment by karthik20** [comment]
Works as expected. Thanks @testforstephen. What's the usual release cycle from pre-release to release?

**Comment by testforstephen** [comment]
0.14.0 is released today, including this fix.
