### ISSUE TITLE
Hot Code Replacement when Launched using the Spring Boot Dashboard

### ISSUE THREAD

**Issue by SSmale** [microsoft/vscode-spring-boot-dashboard#330]
I am using the Sting Boot Dashboard to launch my application in debug and run mode, with the [Spring Boot Dev Tools included in the pom](https://www.baeldung.com/spring-boot-devtools) for auto reloading. 

When have used VS Code for java before and have made us of the [Hot Code Replace](https://github.com/Microsoft/vscode-java-debug/wiki/Hot-Code-Replace) from the debugger ext to seamlessly change the code without stopping and starting the Spring Boot app. The application was run using a launch config.

My question is, how do I using the Dashboard and the hot code replacement together?

**Comment by testforstephen** [comment]
The HCR from Java debugger won't take effect if your application has enabled spring boot dev tools. They cannot use together.
