### ISSUE TITLE
Extension not found at marketplace

### ISSUE THREAD

**Issue by steventong** [Microsoft/vscode-spring-boot-dashboard#34]
https://marketplace.visualstudio.com/search?term=vscode-spring-boot-dashboard&target=VSCode&category=All%20categories&sortBy=Relevance

**Comment by Eskibear** [comment]
The extension has not been released yet. We plan to release in a short time.

**Comment by Eskibear** [comment]
Released [HERE](https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-spring-boot-dashboard)
