### ISSUE TITLE
The running session will shut down and the progress bar is exist, when start multiple apps with one port.

### ISSUE THREAD

**Issue by lxhmavis** [Microsoft/vscode-spring-boot-dashboard#36]
Configurations:
  OS: Windows
  VSCode: 1.27.1
Repro steps:
  1. Start an app, the result as below:
    
![image](https://user-images.githubusercontent.com/41565966/45482206-f9887780-b77f-11e8-9370-7cf584f72c3f.png)

  2. Try to start another one, the running session will shut down and the progress bar is exist, the result as below:
     
![image](https://user-images.githubusercontent.com/41565966/45481977-7109d700-b77f-11e8-8f48-4e2b0a0ec3e6.png)

**Comment by Eskibear** [comment]
I have 2 projects, namely `dogfood`, `onlineshop`, both will listen on port 8080. I cannot reproduce it, see following GIF:

![bootdash-issue](https://user-images.githubusercontent.com/2351748/45483657-2c346f00-b784-11e8-8aae-2bef45f55f9d.gif)

**Comment by lxhmavis** [comment]
The situation is caused by  the two projects are same.
