### ISSUE TITLE
Show/Hide projects from dashboard

### ISSUE THREAD

**Issue by RuiffCardoso** [microsoft/vscode-spring-boot-dashboard#43]
Hi, it would be very usefull if I could hide projects from the spring-boot dashboard.

Simply right clicking and selection to hide would be enough, but if it would be possible to add a regex filter would be excellent.

Thanks

**Comment by kdvolder** [comment]
Can you explain why using the search box at the top, possibly in combination with some tags is not good enough?

I mean that search box + tags, should be able to easily let you focus on a any subset of elements that is interesting to you. If that doesn't work, or it simply isn't convenient enough in some way, it would be good for us to understand exactly why, before we blindly implement some additional filtering mechanic that may still not help your particular use-case.

**Comment by kdvolder** [comment]
> What search box? I can't find any.

Oh sorry, my mistake. I gotten a bit confused, I thought we were talking about STS 4 boot dashboard in **Eclipse**. No fault of yours, since obviously we aren't talking about that here because this issue is in the **vscode**-spring-boot-dashboard issue tracker. Jumping between different projects / trackers sometimes gets a bit confusing.

The Eclipse boot dashboard has searchbox and tagging etc. But the vscode boot dashboard is a bit more limited and there really isn't any 'filtering' mechanic available here yet.

**Comment by RuiffCardoso** [comment]
> > What search box? I can't find any.
> 
> Oh sorry, my mistake. I gotten a bit confused, I thought we were talking about STS 4 boot dashboard in **Eclipse**. No fault of yours, since obviously we aren't talking about that here because this issue is in the **vscode**-spring-boot-dashboard issue tracker. Jumping between different projects / trackers sometimes gets a bit confusing.

Eheh, no problem. If I posted the picture right away I would have helped

> The Eclipse boot dashboard has searchbox and tagging etc. But the vscode boot dashboard is a bit more limited and there really isn't any 'filtering' mechanic available here yet.

Does VSCode support adding searchboxes in this area like Eclipse? Thanks for the feedback =)

**Comment by kdvolder** [comment]
> Does VSCode support adding searchboxes in this area like Eclipse?

I would answer... but I'm not really sure. The good Microsoft folks who built most of this boot dash for vscode might know what's possible in terms of VScode UI here. So I let them take over responding to this ticket from here.

**Comment by Eskibear** [comment]
> Does VSCode support adding searchboxes in this area like Eclipse? Thanks for the feedback =)

VS Code has the search boxes in its "Outline" view, but it hasn't exposed the related APIs yet.

![image](https://user-images.githubusercontent.com/2351748/47056272-1801e880-d1ee-11e8-8578-2cfeddd1cce8.png)

Here is a [feature request](https://github.com/Microsoft/vscode/issues/50062), and I find a related workitem in [VS Code Iteration Plan for October 2018](https://github.com/Microsoft/vscode/issues/60106):
> Tree widget performance improvements & filtering support @joaomoreno

So I suppose it will be available soon.

**Comment by Eskibear** [comment]
VS Code v1.37 supports filtering now. It should be easier to find out the project.
