### ISSUE TITLE
Projects not showing up in "spring boot dashboard"

### ISSUE THREAD

**Issue by shankarramr** [Microsoft/vscode-spring-boot-dashboard#44]
1. I am creating the projects through "spring initializer: generate a maven project".
2. I am setting the group and artifact id.
3. I selecting boot version
4. I am selecting the dependencies

The project gets created and the pop to open it also presents itself. When I click on it it open new vs window with the project properly. But it simply doesn't show up in the "spring boot dashboard" for me to be able to run it.

Java version: JDK 8
VS code: insider 1.29.0

**Comment by Eskibear** [comment]
@shankarramr Currently the project will show up after been successfully built by the language server. For the first time, it may take some time for the language server to download dependencies (it takes time as we all know). Can you wait some time to see if it shows up?

**Comment by shankarramr** [comment]
Hi thanks for the response, I have successfully built the project and I have waited about a month before posting the issue here : )

**Comment by Eskibear** [comment]
I just followed your steps in the latest insider to generate a maven project.  And it works well. 
Can you provide more details like:
* Version of "Language support for Java"
* Boot version and dependencies you selected when generating the project. (Or share the project if possible)

Attaching my mine:
```
VS Code: 1.29.0-insider
Language support for Java: 0.32.0
```

**Comment by shankarramr** [comment]
Hi,

Version of "Language support for Java" - 0.32.0 (October 2nd, 2018)
Boot version - 2018-08-09 (M14)
Dependencies selected - webmvc (I have tried different project/combinations though)

This is just the demo application that the boot application suggests when creating. For some reason I am not able to share the zip file.

**Comment by Eskibear** [comment]
I downloaded your project and had a try, and I just could not reproduce the issue. It first stuck on "importing projects" as expected because the language server was downloading the dependencies. And after <1 min, the project "demo" appeared in the explorer. 

You may have a try of the following steps, but I'm not sure whether it can help you out or not.
1. Close all your VSCode windows. 
2. Open `~/.vscode/extensions` folder, and remove folders with prefix like "redhat.java", "vscjava.vscode-spring-boot-dashboard", "vscjava.vscode-java-debug", "pivotal.vscode-spring-boot". 
3. Open VSCode, install the spring boot dashboard extension from the marketplace. 
4. Now try opening the project again, see if it works.

**Comment by shankarramr** [comment]
Followed your steps (but in the .vscode-insiders folder) and finally it worked.
Looks like corrupt installation or something like that. Please go ahead and close this. Thanks a lot!

**Comment by jjkayani** [comment]
I have tried all the above solutions but still facing the same issue, spring-dashboard is displaying "There is no data provider registered that can provide view data.".

**Comment by solomon-n** [comment]
right click on your pom file and hit update project-- that will do the job

**Comment by mrossioliveira** [comment]
Had the same issue recently and I was able to "fix it" by disabling and then enabling the Spring Boot Dashboard extension in the extensions tab.
After a required reload the project appeared under spring-boot dashboard as expected.

**Comment by uppala-praveen-au7** [comment]
Thanks @mrossioliveira . I too did face the same issue and followed your method and the problem got fixed (at least for now).

**Comment by dvazquez1027** [comment]
I just ran into this same issue. I'm using jenv so I can set the version of Java I use per directory, but I neglected to set the global version from system. I finally noticed the error message in the message window when I start VSCode and realized what was going on. Explicitly setting the java version using jenv global <version #> did the trick for me.

**Comment by Aankhen** [comment]
Same issue here, and none of the previously mentioned solutions is working for me. (VS Code 1.54.3, Windows 10.0.19042, Java 11.0.8.) I’ve seen this before and it usually resolves itself within a day or so or after cleaning the Java workspace and restarting a couple of times, but not this time.

**Comment by fopnet** [comment]
Command 'Spring-Boot Dashboard: Debug ...' resulted in an error (command 'spring-boot-dashboard.localapp.debug-multiple' not found)

Command 'Spring-Boot Dashboard: Start ...' resulted in an error (command 'spring-boot-dashboard.localapp.start-multiple' not found)

- Both command do not work. 
- Spring boot dashboard do not show any projects or debug configuration

**Comment by fopnet** [comment]
Stop working using: 

vscode 1.54.3
spring boot dashboard plugin 0.2.0

<img width="368" alt="Captura de Tela 2021-03-22 às 13 20 41" src="https://user-images.githubusercontent.com/3894473/112022996-9676b900-8b11-11eb-990c-2af1a187a03a.png">

**Comment by Eskibear** [comment]
@fopnet  It depends on below two extensions to detect Spring Boot apps.
* https://marketplace.visualstudio.com/items?itemName=redhat.java
* https://marketplace.visualstudio.com/items?itemName=Pivotal.vscode-spring-boot

Please take a look at status of both extensions. E.g. look at "spring" Output window, see if it's same as https://github.com/spring-projects/sts4/issues/612

**Comment by fopnet** [comment]
> @fopnet It depends on below two extensions to detect Spring Boot apps.
> 
> * https://marketplace.visualstudio.com/items?itemName=redhat.java
> * https://marketplace.visualstudio.com/items?itemName=Pivotal.vscode-spring-boot
> 
> Please take a look at status of both extensions. E.g. look at "spring" Output window, see if it's same as [spring-projects/sts4#612](https://github.com/spring-projects/sts4/issues/612)

When install an extension through VsCode, it automatically install all linked dependencies.
I have tried install a previous version of VsCode and Spring Dashboard too, but both attempts without success

**Comment by Eskibear** [comment]
@fopnet can you point vscode setting `spring-boot.ls.java.home` to your JDK 11, and re-load the window? By mentioning the dependencies, I mean it's possible that the issue occurs because of upstream changes, just as #127 . Let me know if it works.

**Comment by fopnet** [comment]
> @fopnet can you point vscode setting `spring-boot.ls.java.home` to your JDK 11, and re-load the window? By mentioning the dependencies, I mean it's possible that the issue occurs because of upstream changes, just as #127 . Let me know if it works.

I inserted the line below in my settings.json and it works successful.

`"spring-boot.ls.java.home": "/Library/Java/JavaVirtualMachines/jdk-11.0.10.jdk/Contents/Home",`

Question: This verification could be in next plugin version ?

**Comment by Eskibear** [comment]
it depends on when extensino "vscode-spring-boot" ship the fix.

**Comment by Jeff-Tian** [comment]
> right click on your pom file and hit update project-- that will do the job

This works like a charm!

**Comment by saravanajagan** [comment]
> 
> 
> right click on your pom file and hit update project-- that will do the job

It works! thanks alot!

**Comment by fabiodamas** [comment]
If you are using Windows, do the following:

1) Uninstall VS Code.
2) Delete the folder C:\Users\SEU_USUARIO\AppData\Roaming\Code
3) Install the VS Code again.

**Comment by viversba** [comment]
In my case I didn't have the Lombok extension installed and that was causing the Java Extension to malfunction. If you use Lombok on your project make sure you have the extension installed.

**Comment by nillander** [comment]
I I tried to perform the above procedures to clear the extensions folder but the error still persists

**Comment by vunhatchuong** [comment]
I have the same problem, the project showed in "Java Projects" and "Maven" tab, not "Spring Boot Dashboard".

**Comment by AnaGarcia120598** [comment]
I had the same problem, I just changed my spring boot version in my setting.json to a version greater than or equal to 17
![Captura de pantalla 2023-12-26 164152](https://github.com/microsoft/vscode-spring-boot-dashboard/assets/66458895/af7d4a4d-6cc4-420d-b91a-01a9ad851f79)

**Comment by oscarsanzsanchez** [comment]
> Had the same issue recently and I was able to "fix it" by disabling and then enabling the Spring Boot Dashboard extension in the extensions tab. After a required reload the project appeared under spring-boot dashboard as expected. Please note that I am using VS Code Server with WSL2.

Worked!!

**Comment by forna** [comment]
> I had the same problem, I just changed my spring boot version in my setting.json to a version greater than or equal to 17 ![Captura de pantalla 2023-12-26 164152](https://github.com/microsoft/vscode-spring-boot-dashboard/assets/66458895/af7d4a4d-6cc4-420d-b91a-01a9ad851f79)
This fixed it for me.
