### ISSUE TITLE
Support for kotlin project

### ISSUE THREAD

**Issue by anjeludo** [Microsoft/vscode-spring-boot-dashboard#46]
Support for kotlin project?

**Comment by Eskibear** [comment]
First of all, the extension now depends on a language server to recognize a spring-boot project, as far as I know currently there's no implementation of Kotlin language server. 
See: [Language servers](https://microsoft.github.io/language-server-protocol/implementors/servers/)

**Comment by anjeludo** [comment]
Thank you.
