### ISSUE TITLE
Start/Stop a Spring Boot project in the boot dashboard explorer 

### ISSUE THREAD

**Issue by Matthew-Dong** [Microsoft/vscode-spring-boot-dashboard#5]

**Comment by Eskibear** [comment]
My initial idea to implement this feature is to spawn/kill a Java process for an app, just what PR #18 does. And as mentioned in https://github.com/Microsoft/vscode-spring-boot-dashboard/pull/16#issuecomment-408920345 , I also agree that the way to start/stop an app should be implemented as aligned as possible with what java debugger extension does. I notice that VSCode has both `Start debugging` and `Start without debugging` commands, so maybe we can also leverage Java debugger extension to achieve this.

**Comment by Eskibear** [comment]
>  Ideally should be replaced with something using JMX to ask spring boot app to terminate 'nicely'. This may matter, for example, if the app needs to cleanly disconnect from a database.

Yes this might be the best practice. Currently I meet 2 known issues:
* I want to send a signal to ask the app to shutdown 'nicely'
* I want to know the status of the app, e.g. to distinguish `starting` and `running`, to find out the listening port. 
Here I find a [node-jmx](https://github.com/zuazo/node-jmx) lib. From my limited knowledge of JMX, I'm not sure this lib works or not, can you help to take a look?


> While I think it is fine to pick sensible defaults for all these parameters, on the first launch, to keep the ui simple. The user should still be able to control them if they wish.
(how much VM memory it is given, allow user to set extra java system properties, commandline arguments, working directory, environment variables. etc.).

This looks more like the `launch.json` mechanism in VS Code, and that's what Java Debugger has already provided. In Java launch configuration, user can specify what you mentioned via `args`, `vmArgs`, `env`, `cwd`, etc. So I start to feel that the perfect practice is to leverage Java debugger's work.

**Comment by kdvolder** [comment]
> So I start to feel that the perfect practice is to leverage Java debugger's work.

Agreed.

About node-jmx lib... I will try to find some time today or tomorrow to play around with it and see if I can get it to connect to a spring-boot app. Then I'll report back here.

**Comment by kdvolder** [comment]
Reporting back about node-jmx library. 

I've done a lttle experimen and will put the code for that in this repo: https://github.com/kdvolder/node-jmx-experiment

My impression is... I think we can make this library work for us. The api seems a bit awkward in places, especially how it does error handling. 

See issue I raised here: https://github.com/zuazo/node-jmx/issues/19

This may cause some inconveniences for us (as error handling is important, to handle correctly trying to connect to apps that are still in the process of starting or already terminated. But I think we can probably work around it somehow. Also, fixing the api desing probably isn't hard at all, and can be done by fairly trivial changes to the libraries source code. So doing that ourselves via a PR or by forking the project may also be an option.

**Comment by Eskibear** [comment]
For start/stop apps, I want to close this issue because the functionality is already implemented. 

For the JMX topic, let's continue the discussion in https://github.com/Microsoft/vscode-spring-boot-dashboard/issues/8
About how to gracefully stop the app, let's continue the discussion in  https://github.com/Microsoft/vscode-spring-boot-dashboard/issues/19

So I'm now closing this one.
