### ISSUE TITLE
Start Project with different spring profiles

### ISSUE THREAD

**Issue by cptstffn** [microsoft/vscode-spring-boot-dashboard#50]
Hi, 
how can I start different profiles via the dashboard for a specific project? 

For example if you have a application-local.properties - how can I set it up before the run? 

Greetings

**Comment by kdvolder** [comment]
I think you can just add an argument to set the profile to the `launch.json` the dashboard generated for your project. Alternatively you can set 'spring.profiles.active' property in either your application.properties or application.yml. 

Whether you want to set it in launch.json or the properties file would depend on whether you want this profile selected only for the launch from the boot dash (in that case setting via the launch.json) would be the way to go.

In either case you will be selecting the active profiles by setting a spring boot property called 'spring.profiles.active'. This property takes a comma separated list of profile names as a value.

It can be set in a number of different ways. 

Via a commandline argument of the form `--spring.profiles.active=profile1,profile2`.
Via a java system property (so a VM argument of the form `-Dspring.profiles.active=profile1,profile2`.
Via the application.properties or application.yml file on the project's classpath (typically it will be placed in src/main/resources' directory for the typical boot project).

**Comment by mcaulifn** [comment]
@kdvolder - Do you have a sample for setting it in `launch.json`?

**Comment by mcaulifn** [comment]
Got it. Is there a way to inspect other items passed in? For example, I'm passing in a queue name that is supposed to be overriding what is set in the profile. A failed start shows it is picking up the data from the `application-dev.yml` file rather than what is passed in with `vmArgs`.

**Comment by ikilinc** [comment]
The solution introduced  by @Eskibear is very good, for me its enough if you mention this in the docs.

**Comment by likan999** [comment]
I am hit by this issue and I don't understand why this was closed, as none of the solutions really solves the problem IMHO. Did I miss something here?

For the launch.json, it is usually not checked into source control, so if the project is shared with other people, they have to manually modify their own launch.json, which is bad. Also, under git, if I switch the branch, the apps may change, so the launch.json needs to be manually updated every time this happens.

For the suggestion of setting spring.profiles.active in application.properties, it affects the production application.properties so this shouldn't be shared with other people, so everyone works on this has to keep a local change to application.properties, which is also bad.

For the command line argument or environment variable approach, it means we can't use "Spring Boot Dashboard" to start the application but has to run it in terminal, which defeats the purpose of this extension.

Any suggestions?

**Comment by Eskibear** [comment]
> For the launch.json, it is usually not checked into source control

How about checking it in?

**Comment by conghai7** [comment]
> For the launch.json, it is usually not checked into source control, so if the project is shared with other people, they have to manually modify their own launch.json, which is bad.

I agree here.
An alternative approach if you don't mind checking in an .env for development.

`launch.json` (note the `envFile` field):

```json
{
    "configurations": [
        {
            "type": "java",
            "name": "Spring Boot-CommerceShipApiUsersApplication<CommerceShipApiUsers>",
            "request": "launch",
            "cwd": "${workspaceFolder}",
            "mainClass": "com.commerceship.api.CommerceShipApiUsersApplication",
            "projectName": "CommerceShipApiUsers",
            "args": "",
            "envFile": "${workspaceFolder}/.env"
        }
    ]
}
```

`.env`:

```
spring.profiles.active=dev
# other env variables for development, such as:
DB_HOST=...
DB_PORT=...
```

**Comment by Eskibear** [comment]
A good news is, basically it's already supported to run apps with selected profiles. See https://github.com/microsoft/vscode-spring-boot-dashboard/pull/309#issuecomment-1499866377 for the demo.
