### ISSUE TITLE
Only the main class is being compiled

### ISSUE THREAD

**Issue by matheusdallrosa** [Microsoft/vscode-spring-boot-dashboard#66]
I'm starting a spring boot application that i haven't created with the spring initializer extension, the server is going up and i can make requests to it, but only the main Application class is being compiled and i know that because only the Application.class is present on the bin folder, my controllers, services, and repositories are not present on the bin folder.  I'm using gradle.

**Comment by Eskibear** [comment]
[vscode-java](https://github.com/redhat-developer/vscode-java) is responsible for compilation, and [vscode-java-debug](https://github.com/Microsoft/vscode-java-debug) is responsible for starting the service. 

It looks more like a issue of gradle support for vscode-java, as you didn't get other classes compiled. Can you provide your sample project that can stably reproduce the issue?

**Comment by matheusdallrosa** [comment]
I have both vscode-java  and vscode-java-debug  installed.

**Comment by matheusdallrosa** [comment]
I removed all of my spring-boot extensions, installed only Spring Boot Tools and Spring Boot dashboard, and then it worked! Thank you.

**Comment by kdvolder** [comment]
@matheusdallrosa 
> I removed all of my spring-boot extensions,

Just curious, which extensions did you remove exactly?

**Comment by matheusdallrosa** [comment]
I removed Spring Boot Tools, Spring Boot Extension Pack, Spring Boot Dashboard, and Spring Initializr Java Support. After that i only installed Spring Boot Tools and Spring Boot dashboard. I also closed the vscode and opened it again. I forgot to mention that, i'm sorry.

**Comment by matheusdallrosa** [comment]
I have found another case. I'm using the eclipse gradle plugin to generate metadata to the other extension called:  Language Support for Java(TM) by Red Hat

Then i make ./gradlew cleanEclipse it only removes the .classpath and .project files. The .vscode folder remains. I have to remove the .vscode folder so everything work fine. I will try to make a reproducible case.

**Comment by matheusdallrosa** [comment]
- Create a project on https://start.spring.io/ with the following options:
	- Gradle project
	- Java language
	- Spring boot 2.1.3
	- Web dependency.

- Open the project with vscode.

- Add the eclipse plugin the the build.gradle file.

- create a package inside the page that contains the main class and make a controller with one simple route.

- run: ./gradlew eclipse

- run: ./gradlew bootRun

- stop the server.

- remove the bin and build folders that gradle generated.

- Try to start the app with the spring-boot dashboard and it won't work.

My vscode shows the message: Error: Could not find or load main class com.example.demo.DemoApplication , on the DEBUG CONSOLE.

**Comment by Eskibear** [comment]
> remove the bin and build folders that gradle generated.

This step is the culprit. 


When you start the app in boot dashboard, the dashboard actually requests "Debugger for Java" to start the session, and the debugger will also request "Language support for Java" to **incrementally** build the project, in order to apply your latest code changes. 

When you remove the `bin/` **manually**, "Language support for Java" has no knowledge about the removal, it's out-of-sync. In such case, you should tell it to do a full compilation to re-generate the .class files. 

i.e. **Command Palette** -> **Java: Force Java compilation** -> **Full**

**Comment by matheusdallrosa** [comment]
Thank you. I have to remove bin/ and build/ manually when "Language support for Java" doesn't recognize some class that i created. Now i will follow your advice and use the command you gave.
