### ISSUE TITLE
use maven profile on files changed

### ISSUE THREAD

**Issue by ayazhussein** [Microsoft/vscode-spring-boot-dashboard#67]
Hello, 

I'm using maven profile in a project and if I add a prelaunch task with ```mvn instal -Pprofile``` the server starts and everything works but once I change a line and trigger a server restart, it stops working because it doesn't rebuild with maven profile. 

I tried setting args in launch.json but it doesn't help, I also set the ```-Pprofile``` as default option to all Maven commands but it still doesn't work.

**Comment by Eskibear** [comment]
I tried the preLaunchTask and it seems to work well. Every time I start/restart the project, the task is 
```json
        {
            "label": "hahaha",
            "type": "shell",
            "command":["pwd"],
            "options": {
                "cwd": "${workspaceFolder}"
            }
        }
```
log:
```
> Executing task: pwd <

/c/Users/yanzh/Work/spring-petclinic

Terminal will be reused by tasks, press any key to close it.

###<--- NOW I CLICK RESTART BUTTON

> Executing task: pwd <

/c/Users/yanzh/Work/spring-petclinic

Terminal will be reused by tasks, press any key to close it.
```

> but once I change a line and trigger a server restart

Were you clicking the refresh button?

**Comment by ayazhussein** [comment]
Somehow after completely uninstalling Visual Studio Code and Installing it again, it works now
I was having an issue where the profile from `~/.m2/settings.xml` was not taken into consideration but now it works.
I tried to replicate it but no success.

**Comment by Eskibear** [comment]
Good to know that. Closing it now.
