### ISSUE TITLE
spring boot dashboard not showing project

### ISSUE THREAD

**Issue by maheshloya-aegon** [microsoft/vscode-spring-boot-dashboard#69]
Issue Type: <b>Bug</b>

command 'spring-boot-dashboard.localapp.start-multiple' not found

Extension version: 0.1.5
VS Code version: Code 1.36.1 (2213894ea0415ee8c85c5eea0d0ff81ecc191529, 2019-07-08T22:59:35.033Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (6.32GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by Eskibear** [comment]
It looks that the extension is not activated. 
Currently activation events include [these](https://github.com/microsoft/vscode-spring-boot-dashboard/blob/c0aa785a0b8e9ecc047eb244530c6a4dda89a25d/package.json#L22-L25). If you click to expand the project explorer, the extension should be automatically activated. 

Can you provide more details, like the steps to repro the issue? Thanks.
