### ISSUE TITLE
Renaming project on Spring Boot Dashboard does not seem to be possible

### ISSUE THREAD

**Issue by masbaehr** [microsoft/vscode-spring-boot-dashboard#75]
Hi, I think the name of the project which is shown in the dashboard should be taken from the project information and not cached somewhere. 

I've also tried to search the temp files but didn't find the spot where i can change it

![image](https://user-images.githubusercontent.com/38694044/63148159-9d1d8000-c000-11e9-9864-e64e758fdec3.png)

![image](https://user-images.githubusercontent.com/38694044/63148169-a73f7e80-c000-11e9-9905-9d14539469c1.png)

**Comment by Eskibear** [comment]
This extension (spring-boot-dashboard) doesn't cache project information. All the information is coming from [Spring Tools extension](https://github.com/spring-projects/sts4/tree/master/vscode-extensions/vscode-spring-boot), which might be originally from the [Java extension](https://github.com/redhat-developer/vscode-java).  

Try cleaning the Java workspace? 
<img width="652" alt="Screen Shot 2019-08-16 at 8 23 08 PM" src="https://user-images.githubusercontent.com/2351748/63167375-b7d51080-c063-11e9-8db1-70a0da13c096.png">

**Comment by masbaehr** [comment]
Ok thanks for the info obviously this would work (and indeed it does work) but if one decides to rename the project, the workspace has to be cleaned which does a not of other things and uses a lot of traffic does not feel like a nice solution. Adding a "Rename" feature could be useful in my opinion. Though feel free to close this issue if this is the wrong place to ask for it :)

**Comment by Eskibear** [comment]
If the project is a Maven project, right click on pom.xml, there is an entry "Update project configuration", which is also possible to update the project name WITHOUT cleaning the whole workspace. You may give it a try. 

[redhat-developer/vscode-java](https://github.com/redhat-developer/vscode-java) is probably a better place for the issue. I'm closing this one, and you can open an issue there to get more professional help for the Java extension.
