### ISSUE TITLE
Extension host terminated unexpectedly

### ISSUE THREAD

**Issue by kishorsn77** [microsoft/vscode-spring-boot-dashboard#76]
Issue Type: <b>Bug</b>

Steps:
1. Open any java maven project
2. As soon as the folder is loaded, there is a pop up message saying "Extension host terminated unexpectly".
3. Maven project dependencies are not loaded. Project doesn't show up under Spring-Dashboard and under Maven projects

Expected:
No pop up message and the code should load maven dependencies without any issues

Actual:
1. Message pop up showing "Extension host terminated unexpectedly".
2. Maven project dependencies are not loaded. Project doesn't show up under Spring-Dashboard and under Maven projects.

VS Code version: 1.37.1
OS: Win10
Electron: 4.2.7

Extension version: 0.1.6
VS Code version: Code 1.37.1 (f06011ac164ae4dc8e753a3fe7f9549844d15e35, 2019-08-15T16:17:55.855Z)
OS version: Windows_NT x64 10.0.17134

**Comment by Eskibear** [comment]
> ... any java maven project

It looks not that convincing. 

> a pop up message saying "Extension host terminated unexpectly".

I guess one of your extensions crashed. Is there any suspect?


This extension depends on [Java extension](https://github.com/redhat-developer/vscode-java), and all the compilation is done by that extension. But as far as I know, it works well for most Maven projects. So can you have a try again with other unrelated extensions disabled?

**Comment by kishorsn77** [comment]
I could find the extension causing the issue. It is "Java Language Support"(George Fraser). After uninstalling it, the popup went away and vscode is working normally.

**Comment by Eskibear** [comment]
Good to know it. I'm closing it now.

**Comment by chetan-kashyap** [comment]
> I could find the extension causing the issue. It is "Java Language Support"(George Fraser). After uninstalling it, the popup went away and vscode is working normally.

OMG it worked .........dude, you're awesome
