### ISSUE TITLE
Spring boot project is not loaded at dashboard.

### ISSUE THREAD

**Issue by matujuri** [microsoft/vscode-spring-boot-dashboard#88]
The error message is as follows:
> Error trying to find JVM: TypeError: Cannot read property 'isJdk' of null

I'm not sure if it affects that I just installed `jdk-13.0.1`.

Waiting for the answer. Thank you!

**Comment by mar1ged** [comment]
I have the exact same issue, but with JDK 11. How did you solve your issue ?

**Comment by ArunMeghanathan97** [comment]
just i was remove all spring boot extension from vs code and then reinstall all extension again then it's working perfectly.
