### ISSUE TITLE
Start button should start app immediately if there is only one app

### ISSUE THREAD

**Issue by jmbockhorst** [microsoft/vscode-spring-boot-dashboard#90]
When there is only one app, the start button should start that app immediately, instead of showing the dialog.

**Comment by Eskibear** [comment]
It makes some sense. But, current behavior has a benefit, it's providing a kind of confirmation mechanism, in case of clicking by mistake. 

PR is welcome, related code is
https://github.com/microsoft/vscode-spring-boot-dashboard/blob/db267808975cc66a3741a2c9a75862d85c5c659f/src/Controller.ts#L28-L35
