### ISSUE TITLE
command 'spring-boot-dashboard.refresh' not found

### ISSUE THREAD

**Issue by balaji043** [microsoft/vscode-spring-boot-dashboard#92]
Issue Type: <b>Bug</b>

1. Install spring-boot-dashboard
2. Create a new project
3. click on Spring-boot-dashoard icons refresh or start

Extension version: 0.1.6
VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:45.096Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (2.47GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by Eskibear** [comment]
It should have been activated, as defined below.
https://github.com/microsoft/vscode-spring-boot-dashboard/blob/c3bf0fa33cf4c8799094bbf7c48d4b42edf6d5fc/package.json#L22-L25

Can you paste full log from `Log (Extension Host)` ?

![image](https://user-images.githubusercontent.com/2351748/71569889-18458580-2b0d-11ea-847a-7cfe8cac5031.png)
