### ISSUE TITLE
Consider adding `-Dspring.jmx.enabled=true` JVM arg automatically

### ISSUE THREAD

**Issue by kdvolder** [microsoft/vscode-spring-boot-dashboard#93]
This is no longer enabled automatically by spring boot itself:

See: https://github.com/spring-projects/spring-boot/issues/16090

This interferes with some features of the spring boot tooling that relies on it (i.e. live hovers). While users can work around this by enabling it themselves, it can be confusing and annoying. 

See: https://github.com/spring-projects/sts4/issues/395

So perhaps it is a good idea if, when boot dashboard creates a new Java launch configuration, then it can automatically add a vmArg setting system property `-Dspring.jmx.enabled=true` to enable it.

**Comment by Eskibear** [comment]
It makes sense.

**Comment by Eskibear** [comment]
shipped with v0.1.7
