### ISSUE TITLE
Can't get projects to show in spring-boot dashboard after git

### ISSUE THREAD

**Issue by mattisking** [microsoft/vscode-spring-boot-dashboard#98]
I made a local copy of a project that was properly working using the latest version of the spring-boot dashboard. On my non-backup copy I added my project to git in an initial commit, created a develop branch, then checked out.

I can operate on the project using Maven, however nothing will make it show up in the dashboard which worked before git.

I open the backup copy and the projects show up, but not in the official version. I cleaned EVERYTHING and still nothing. 

I installed the  Compare Folders extension and the only differences are in the .git folder.

Uploading the project to you won't help. It's using some enterprise packages hosted internally in Nexus. Is there some logging somewhere I can look at to try and figure out what's going on?

**Comment by mattisking** [comment]
I went through and totally wiped maven

mvn dependency:purge-local-repository
I backed up the files in the project including .git folder, created a new folder and put them back. That makes no sense but it's Windows and who knows. The Java Dependencies plugin was showing nonsense so something very odd was happening.

I went back in and did:
mvn clean install -U

and it's working. No idea.

**Comment by Eskibear** [comment]
The dashboard depends on Java extension to tell if its a spring-boot projects, so does the Java Dependencies extension. A reasonable guess is, the git operation involves lots of file changes in a second, causing chaos in Java extension... 
See https://github.com/redhat-developer/vscode-java/issues/1280

For the moment, if you meet the issue again, below command might probably help:

> `Java:Clean the Java language server workspace`: Clean the Java language server workspace.
